
name: Update GitHub Stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=Leandro-Pinheiro-Dev&show_icons=true&theme=gruvbox_light
          path: profile/stats.svg
          git push

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=Leandro-Pinheiro-Dev&layout=compact&theme=gruvbox_light
          path: profile/top-langs.svg
          git push
